image: alpine:latest

pages:
  stage: deploy
  script:
  - echo 'go go go...'
  - rm -rf public
  - mkdir public
  - find * -maxdepth 0 -iname 'task*' -exec cp -r {} public/{} \;
  artifacts:
    paths:
    - public
  only:
  - master
